image: Ubuntu1804 # образ для сборки

stack: node 12 # окружение

branches:
  only:
    - master # ветка git

cache: node_modules # кеширование

install:
  - npm install # команда установки зависимостей

build: off

build_script:
  - npm run build # команда сборки

test_script:
  - npm run lint && npm test # скрипт сборки
deploy_script: # скрипт развёртывания
- git config --global credential.helper store
- git config --global Nikolaev Artem AppVeyor
- git config --global artem_nikolaev69@mail.ru ci@appveyor.com
- echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
- npx push-dir --dir=dist --branch=gh-pages --force --verbose